### ISSUE TITLE
ev3dev-bionic build failing on GitHub Actions

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricks-micropython#12]
This started failing today. The failure occurs when running `make -C bricks/ev3dev test-ev3dev`. It does not fail locally for me.

Error from GitHub actions:

```
make: Entering directory '/home/runner/work/pybricks-micropython/pybricks-micropython/bricks/ev3dev'
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
cd ../../micropython/tests && MICROPY_MICROPYTHON="../../tests/ev3dev/test-wrapper.sh" \
	GRX_PLUGIN_PATH=/home/runner/work/pybricks-micropython/pybricks-micropython/bricks/ev3dev/build GRX_DRIVER=test \
	./run-tests --test-dirs ../../tests/ev3dev/brick ../../tests/ev3dev/experimental ../../tests/ev3dev/media ../../tests/ev3dev/messaging ../../tests/ev3dev/motor ../../tests/ev3dev/parameters
Traceback (most recent call last):
  File "./run-tests", line 678, in <module>
    main()
  File "./run-tests", line 669, in main
    res = run_tests(pyb, tests, args, base_path)
  File "./run-tests", line 307, in run_tests
    upy_float_precision = int(upy_float_precision)
ValueError: invalid literal for int() with base 10: b'udev_enumerate_add_match_subsystem failed: No such file or directory\n64\n'
make: *** [test-ev3dev] Error 1
Makefile:377: recipe for target 'test-ev3dev' failed
```

Possibly caused by rollout of [GitHub actions update](https://github.com/actions/virtual-environments/blob/releases/ubuntu18/20200817/images/linux/Ubuntu1804-README.md). Not seeing anything in the changelog that looks suspicious though.

I'm guessing something from the update (security?) is preventing [umockdev](https://github.com/martinpitt/umockdev) from working correctly.

**Comment by dlech** [comment]
The error message was incorrect. Correct message is:

    ValueError: invalid literal for int() with base 10: b'udev_enumerate_scan_devices failed: No such file or directory\n64\n'

Sounds like this bug: https://github.com/systemd/systemd/issues/13814

**Comment by dlech** [comment]
Ubuntu released a [new version of umockdev in bionic-updates](https://packages.ubuntu.com/source/bionic-updates/umockdev). This had precedence over the [patched umockdev package from ev3dev](https://github.com/ev3dev/umockdev).

The ev3dev package has been updated to extend the newer upstream package.

**Comment by dlech** [comment]
CI builds are green again after updating the ev3dev umocdev package

**Comment by dlech** [comment]
> The error message was incorrect.

fixed by https://github.com/pybricks/pybricks-micropython/commit/b1100114ed1fdceefafc8be2735662e27df62ffc
